name: federico.balistreri
description: paradigm
version: 0.0.1
author: vjootv2z.rzouajf2@fuid9aug.com
language: scala
buildSystem: ''
buildSystemDetails:
  artefactID: federicobalistreri
  parentArtefactID: ''
  buildSystem: maven
  author: null
  createdAt: '2024-12-08 20:23:36'
pipelines:
  pipelines/Carin_RempelMegan_BaconDodie_Fahey:
    name: Carin_RempelMegan_BaconDodie_Fahey
    description: null
    author: vjootv2z.rzouajf2@fuid9aug.com
    mode: batch
    artefactID: ''
    language: scala
    createdAt: '2024-12-08 20:23:36'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
gemContainer:
  languageVersion: 2.12.15
  gemLibsVersion: 1.1.26
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-12-08 20:23:36'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2024-12-08T20:23:36.937293Z'
  name: plibMaven
  version: 8.7.0-SNAPSHOT
  id: '111010929'
  createdAt: '2024-12-08T20:23:36.937293Z'
  type: plibMaven
projectDependencies: {}
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
